language: rust

matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly

stages:
- info
- build
- test

jobs:
  include:
  - stage: info
    script: rustc --version && cargo --version
    
  - stage: build
    script: cargo build
    
  - stage: test
    script: cargo test
